trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    inputs:
      version: '18.x'
  - script: npm install
    displayName: 'Install dependencies'
  - script: npm test
    displayName: 'Run Tests'
  - script: npm run build
    displayName: 'Build Application'
